# Prevent screen from going off
xset s off
xset -dpms
xset s noblank

# Start default programs
feh --bg-scale ~/.config/i3/wallpapers/Default*
pgrep xbanish    &> /dev/null || xbanish &
pgrep pulseaudio &> /dev/null || pulseaudio -D
#pgrep dropbox    &> /dev/null || dropbox &> /dev/null &
pgrep compton    &> /dev/null || compton &

synclient TapButton1=1
loadkeys de
setxkbmap de
xdg-user-dirs-update
xdg-user-dirs-gtk-update
exec i3
