# Prevent screen from going off
xset s off
xset -dpms
xset s noblank

# Kill processes
pkill -9 compton
pkill -9 pulseaudio
pkill -9 xbanish

# Start default programs
feh --bg-scale ~/.config/i3/wallpapers/Default*
xbanish &
compton &
pulseaudio --start -D

synclient TapButton1=1
setxkbmap de
xdg-user-dirs-update
xdg-user-dirs-gtk-update
exec i3
