# Prevent screen from going off
xset s off
xset -dpms
xset s noblank

# Start default programs
feh --bg-scale ~/.config/i3/wallpapers/Default*
pgrep xbanish &> /dev/null || xbanish &
pgrep compton &> /dev/null || compton &
pulseaudio --check && pulseaudio --kill
pulseaudio --start -D

synclient TapButton1=1
setxkbmap de
xdg-user-dirs-update
xdg-user-dirs-gtk-update
exec i3
